dependencies:
- name: certificates
  version: "0.0.1"
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
- name: traefik
  version: 10.14.2
  repository: "https://helm.traefik.io/traefik"
