gateway:
  image:
    ## Define the image for the auth middleware
    auth:
      repository: renku/renku-gateway
      tag: "latest"

  reverseProxy:
    image:
      repository: renku/renku-revproxy
      tag: "latest"
