FROM golang:1.19.5-alpine3.17 as builder
WORKDIR /src
COPY go.mod go.sum ./
COPY cmd/revproxy/ ./
RUN go build -o /revproxy

FROM alpine:3.17
USER 1000:1000
COPY --from=builder /revproxy /revproxy
ENTRYPOINT [ "/revproxy" ]
