services:
  gateway:
    image: "mcr.microsoft.com/devcontainers/go:2-1.26"
    volumes:
      - ../:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    entrypoint: sleep infinity
    environment:
      CONFIG_LOCATION: /workspace/internal/config
      GATEWAY_POSTGRES_HOST: 127.0.0.1
      GATEWAY_POSTGRES_DATABASE: renku_gateway
      GATEWAY_POSTGRES_USERNAME: renku_gateway
      GATEWAY_POSTGRES_PASSWORD: renku_gateway
    network_mode: service:db
    depends_on:
      - db
    group_add:
      - "8983" # Allows access to the solr data in the shared volume

  db:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ./generate_ulid_func.sql
        target: /docker-entrypoint-initdb.d/generate_ulid_func.sql
    environment:
      POSTGRES_USER: renku_gateway
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: renku_gateway
    ports:
      - "5432:5432" # postgresql

volumes:
  postgres-data:
