# Example values for configuration
server:
  port: 8080
  allowOrigin: []
  host: 0.0.0.0
  rateLimits:
    enabled: false
    rate:
    burst:
revproxy:
  renkuBaseUrl: "https://renkulab.io"
  externalGitlabUrl:
  k8sNamespace:
  renkuServices:
    noteboooks:
    kg:
    webhoook:
    core:
      serviceNames: []
      servicePaths: []
      sticky: 
    auth:
    dataService:
    keycloak:
login:
  endpointsBasePath: 
  defaultAppRedirectURL: 
  tokenEncryption:
    enabled: true
    secretKey:
  providers:
    id1:
      default: true
      issuer: https://renkulab.io/auth/realms/Renku
      clientID: renku
      clientSecret: 
      scopes: []
      callbackURI: https://renkulab.io/api/auth/callback
      # For securely handling callbacks an encoding and hashing of 32 bytes should be provided
      cookieEncodingKey: 
      cookieHashKey:
      usePKCE: false
redis:
  type: dummy 
  addresses: []
  isSentinel: false
  password:
  masterName:
  dbIndex: 1
monitoring:
  sentry:
    enabled: false
    dsn: 
    environment: gateway
    sampleRate: 0.1
  prometheus:
    enabled: true
    port: 8005

