login:
  tokenEncryption:
    secretKey: secret-key-from-secret-file 
  providers:
    id1:
      clientSecret: client-secret-from-secret-file 
      cookieEncodingKey: enc-key-from-secret-file 
      cookieHashKey: hash-key-from-secret-file

