openapi: 3.0.2
info:
  title: Renku gateway
  description: Login flow, OAuth callbacks and authentication for Renku
  version: v1
servers:
  - url: /api/auth
paths:
  /:
    servers:
      - url: http://renku-gateway-auth
        description: Available only from within the k8s cluster
    get:
      description: Supports traefik authentication middleware.
      parameters:
        - in: query
          name: auth
          schema:
            type: string
            enum: 
              - gitlab
              - renku
              - notebook
              - cli-gitlab
      responses:
        '200':
          description: |
            If there is no auth query parameter then the response is completely empty.
            If the auth query parameter is specificed then this indicates that the user
            was successfully authenticated and that any required credentials have
            been injected in the repsonse header.
        '401':
          description: The user cannot be authenticated for the specific request
      tags:
        - traefik
  /health:
    servers:
      - url: http://renku-gateway-auth
        description: Available only from within the k8s cluster
    get:
      description: Healthcheck endpoint.
      responses:
        '200':
          description: The service is running properly.
      tags:
        - traefik
  /login:
    get:
      description: Starts the login process for Renku.
      parameters:
        - in: query
          name: redirect_url
          required: true 
          schema:
            type: string
      responses:
        '302':
          description: The user is redirected to the proper login page.
      tags:
        - renku
  /login/next:
    get:
      description: Redirect to the next authentication step
      responses:
        '200':
          description: Move on to the next login step via the client session
        '302':
          description: Redirect to the protected page
      tags:
        - renku
  /token:
    get:
      description: Authorization code flow callback
      parameters:
        - in: query
          name: code
          required: true 
          schema:
            type: string
        - in: query
          name: state
          required: true 
          schema:
            type: string
        - in: query
          name: session_state
          required: false 
          schema:
            type: string
      responses:
        '302':
          description: The token was used to acquire the access token and the request is redirected further
      tags:
        - renku
  /logout:
    get:
      description: |
        Log the user out of Renku. Depending on the configuration of the gateway 
        this can result in the user also being logged out of Gitlab.
      responses:
        '200':
          description: The user was successfully logged out
      tags:
        - renku
  /user-profile:
    get:
      description: Redirect to the Keycloak user profile settings page.
      responses:
        '302':
          description: The user profile page
          content: 
            text/html: {}
      tags:
        - renku
  /gitlab/login:
    get:
      description: Starts the login process for the Gitlab deployment associated with Renku.
      responses:
        '302':
          description: The user is redirected to the proper login page.
      tags:
        - gitlab
  /gitlab/token:
    get:
      description: Starts the login process for the Gitlab deployment associated with Renku.
      responses:
        '302':
          description: The user is redirected to the proper login page.
      tags:
        - gitlab
  /gitlab/logout:
    get:
      description: Logs the user out of Gitlab.
      responses:
        '200':
          description: The user was successfully logged out.
      tags:
        - gitlab
  /cli-token:
    get:
      description: Exchange a cli_nonce and sever_nonce for an access token.
      parameters:
        - in: query
          name: cli_nonce
          schema:
            type: string
          required: true
        - in: query
          name: server_nonce
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Return the access token for the user
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/CLIResponseAccessToken'
        '403':
          description: Session expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CLIResponseErrorMessage'
      tags:
        - cli
  /cli/login:
    get:
      description: Starts the login process for the the CLI.
      responses:
        '302':
          description: The user is redirected to the proper login page.
      tags:
        - cli
  /cli/token:
    get:
      description: Callback endpoint for logging in with the CLI.
      responses:
        '302':
          description: The user is redirected to the proper login page or content.
      tags:
        - cli
  /cli/logout:
    get:
      description: This does nothing
      responses:
        '200':
          description: Empty response
      tags:
        - cli
components:
  schemas:
    CLIResponseErrorMessage:
      properties:
        error:
          type: string
      required:
        - error
      type: object
    CLIResponseAccessToken:
      properties:
        access_token:
          type: string
      required:
        - access_token
      type: object