name: tests
on:
  pull_request: {}
permissions:
  contents: read
jobs:
  unit-tests:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: test
        run: go test ./... -v
