---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  traefik.toml: |
    {{ if .Values.development }}
    [log]
      level = "DEBUG"
    {{ else }}
    [log]
      level = "ERROR"
    {{ end }}

    [api]
      dashboard = true

    [providers]
      [providers.file]
        directory = "/config"

    [entrypoints]
      [entrypoints.http]
        address = ":{{ .Values.service.port }}"

    [accessLog]
      bufferingSize = 10

  rules.toml: |
    [http]
      [http.routers]
        [http.routers.apiRedirect]
          entryPoints = ["http"]
          Middlewares = ["apiRediredctEncodeSlash", "apiRedirect"]
          Rule = "PathPrefix(`/entities`) && HeadersRegexp(`Accept`,`application/json`)"
          Service = "default"

        [http.routers.uiRedirect]
          entryPoints = ["http"]
          Middlewares = ["uiRedirect"]
          Rule = "PathPrefix(`/entities`) && HeadersRegexp(`Accept`,`text/html`)"
          Service = "default"

        [http.routers.gateway]
          entryPoints = ["http"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}auth`)"
          Service = "gateway"

        [http.routers.notebooks]
          entryPoints = ["http"]
          Middlewares = ["auth-notebook", "common"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}notebooks`)"
          Service = "notebooks"

        [http.routers.jupyterhub-compat]
          entryPoints = ["http"]
          Middlewares = ["jupyterhub-compat", "auth-notebook", "common"]
          Rule = "PathPrefix(`/jupyterhub/services/notebooks`)"
          Service = "notebooks"

        [http.routers.webhooks]
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "webhooks"]
          Rule = "Path(`{{ .Values.gatewayServicePrefix | default "/api/" }}projects/{project-id}/graph/webhooks{endpoint:(.*)}`)"
          Service = "webhooks"

        [http.routers.graphstatus]
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "graphstatus"]
          Rule = "Path(`{{ .Values.gatewayServicePrefix | default "/api/" }}projects/{project-id}/graph/status{endpoint:(.*)}`)"
          Service = "webhooks"

        [http.routers.datasets]
          entryPoints = ["http"]
          Middlewares = ["common", "knowledgeGraph"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}datasets`)"
          Service = "knowledgeGraph"

        [http.routers.direct]
          # This is to access undocumented APIs in GitLab
          entryPoints = ["http"]
          Middlewares = [
            "direct"
            {{- if .Values.global.gitlab.urlPrefix -}}
            {{- if and (ne .Values.global.gitlab.urlPrefix "") (ne .Values.global.gitlab.urlPrefix "/") -}}
            ,"gitlabOnly"
            {{- end -}}
            {{- end }}
          ]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}direct/`)"
          Service = "gitlab"
        
        [http.routers.gitlabGraphql]
          entryPoints = ["http"]
          Middlewares = [
            "auth-gitlab","general-ratelimit","api"
            {{- if .Values.global.gitlab.urlPrefix -}}
            {{- if and (ne .Values.global.gitlab.urlPrefix "") (ne .Values.global.gitlab.urlPrefix "/") -}}
            ,"gitlabOnly"
            {{- end -}}
            {{- end }}
            ,"gitlabGraphql"
          ]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}graphql`)"
          Service = "gitlab"

        [http.routers.gitlab]
          # Currently gitlab acts as fallback backend service, we
          # therefore fix the priority of this router to the lowest
          # possible value.
          priority = 1
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "gitlabApi"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}`)"
          Service = "gitlab"

        [http.routers.gitlabRenkuCli]
          # Access to gitlab server from a git repo with CLI token
          entryPoints = ["http"]
          Middlewares = ["auth-cliGitlab", "common", "cliGitlab"]
          Rule = "PathPrefix(`{{ .Values.global.gitlab.cliUrlPrefix | default "/repos/" }}`)"
          Service = "gitlab"

        [http.routers.renku]
          entryPoints = ["http"]
          Middlewares = ["auth-renku", "common"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}renku`)"
          Service = "core"

        [http.routers.kg]
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "kg", "knowledgeGraph"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}kg`)"
          Service = "knowledgeGraph"

      [http.middlewares]

        # We assume entity IDs which are URL-safe except <namespace>/<project-name>
        # IDs (so all IDs with one forward-slash) for projets which we capture and
        # URL-encode explicitly. Full URL-encoding is tricky with GO regexes.
        [http.middlewares.apiRediredctEncodeSlash.redirectRegex]
          regex = "http://(.*)/entities/([^/]*)/([^/]*)/(.*)"
          replacement = "{{(include "gateway.protocol" .)}}://${1}/api/${2}/${3}%2F${4}"

        [http.middlewares.apiRedirect.redirectRegex]
          regex = "http://(.*)/entities/(.*)"
          replacement = "{{(include "gateway.protocol" .)}}://${1}/api/${2}"

        [http.middlewares.uiRedirect.redirectRegex]
          regex = "http://(.*)/entities/(.*)"
          replacement = "{{(include "gateway.protocol" .)}}://${1}/${2}"

        [http.middlewares.commonWithCookie.chain]
          {{- if .Values.development }}
          middlewares = ["general-ratelimit", "api", "development"]
          {{- else }}
          middlewares = ["general-ratelimit", "api"]
          {{- end }}

        [http.middlewares.common.chain]
          middlewares = ["noCookies", "commonWithCookie"]

        [http.middlewares.noCookies.headers]
          [http.middlewares.noCookies.headers.CustomRequestHeaders]
            Cookie = ""

        [http.middlewares.api.StripPrefix]
          prefixes = ["/api"]

        [http.middlewares.development.headers]
          isDevelopment = true

        [http.middlewares.gitlabOnly.AddPrefix]
          prefix = "{{ .Values.global.gitlab.urlPrefix }}"

        [http.middlewares.gitlabApi.AddPrefix]
          {{ if eq .Values.global.gitlab.urlPrefix "/" }}
          prefix = "/api/v4"
          {{- else -}}
          prefix = "{{ .Values.global.gitlab.urlPrefix }}/api/v4"
          {{ end }}

        [http.middlewares.cliGitlab.ReplacePathRegex]
          regex = "^/repos/(.*)"
          {{ if eq .Values.global.gitlab.urlPrefix "/" }}
          replacement = "/$1"
          {{- else -}}
          replacement = "{{ .Values.global.gitlab.urlPrefix }}/$1"
          {{ end }}

        [http.middlewares.auth-gitlab.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=gitlab"
          trustForwardHeader = true
          authResponseHeaders = ["Authorization"]

        [http.middlewares.auth-cliGitlab.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=cli-gitlab"
          trustForwardHeader = true
          authResponseHeaders = ["Authorization"]

        [http.middlewares.auth-renku.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=renku"
          trustForwardHeader = true
          authResponseHeaders = ["Authorization", "Renku-user-id", "Renku-user-fullname", "Renku-user-email"]

        [http.middlewares.auth-notebook.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=notebook"
          trustForwardHeader = true
    {{ if .Values.global.anonymousSessions.enabled }}
          authResponseHeaders = ["Renku-Auth-Access-Token", "Renku-Auth-Id-Token", "Renku-Auth-Git-Credentials", "Renku-Auth-Anon-Id"]
    {{ else }}
          authResponseHeaders = ["Renku-Auth-Access-Token", "Renku-Auth-Id-Token", "Renku-Auth-Git-Credentials"]
    {{ end }}

        [http.middlewares.webhooks.ReplacePathRegex]
          regex = "^/projects/([^/]*)/graph/webhooks(.*)"
          replacement = "/projects/$1/webhooks$2"

        [http.middlewares.graphstatus.ReplacePathRegex]
          regex = "^/projects/([^/]*)/graph(.*)"
          replacement = "/projects/$1/events$2"

        [http.middlewares.jupyterhub-compat.ReplacePathRegex]
          regex = "^/jupyterhub/services/notebooks/(.*)"
          replacement = "{{ .Values.gatewayServicePrefix | default "/api/" }}notebooks/$1"

        [http.middlewares.kg.StripPrefix]
          prefixes = ["/kg"]

        [http.middlewares.knowledgeGraph.AddPrefix]
          prefix = "/knowledge-graph"

        [http.middlewares.direct.ReplacePathRegex]
          regex = "^/api/direct/(.*)"
          replacement = "/$1"

        [http.middlewares.gitlabGraphql.ReplacePathRegex]
          regex = "(.*)/graphql(.*)"
          replacement = "/$1/api/graphql$2"

        [http.middlewares.general-ratelimit.ratelimit]
          extractorfunc = "{{ .Values.rateLimits.general.extractorfunc }}"
          [http.middlewares.general-ratelimit.ratelimit.rateset.rate0]
            period = "{{ .Values.rateLimits.general.period }}"
            average = {{ .Values.rateLimits.general.average }}
            burst = {{ .Values.rateLimits.general.burst }}

      [http.services]
        [http.services.gateway.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.gateway.LoadBalancer.servers]]
            url = "http://{{ template "gateway.fullname" . }}-auth/"
            weight = 1

        [http.services.gitlab.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.gitlab.LoadBalancer.servers]]
            url = {{ .Values.gitlabUrl | default (printf "%s://%s/gitlab" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            weight = 1

        [http.services.notebooks.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.notebooks.LoadBalancer.servers]]
            url = {{ .Values.notebooks.hostname | default (printf "http://%s-notebooks" .Release.Name )  | quote }}
            weight = 1

        [http.services.webhooks.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.webhooks.LoadBalancer.servers]]
            url = {{ .Values.graph.webhookService.hostname | default (printf "http://%s-webhook-service" .Release.Name ) | quote }}
            weight = 1

        [http.services.knowledgeGraph.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.knowledgeGraph.LoadBalancer.servers]]
          url = {{ .Values.graph.knowledgeGraph.hostname | default (printf "http://%s-knowledge-graph" .Release.Name ) | quote }}
            weight = 1

        [http.services.core.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.core.LoadBalancer.servers]]
          url = {{ .Values.core.hostname | default (printf "http://%s-core" .Release.Name ) | quote }}
            weight = 1

        # We need a default backend, should never be hit
        [http.services.default.LoadBalancer]
          method = "drr"
          [[http.services.default.LoadBalancer.servers]]
          url = {{ printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain | quote }}
            weight = 1
