---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  traefik.toml: |
    {{ if .Values.development }}
    [Global]
      debug = true

    [log]
      level = "debug"
    {{ else }}
    [log]
      level = "error"
    {{ end }}

    [api]
      dashboard = true

    [providers]
      [providers.file]
        directory = "/config"

    [entrypoints]
      [entrypoints.http]
        address = ":{{ .Values.service.port }}"

    [accessLog]
      bufferingSize = 10

  rules.toml: |
    [http]
      [http.routers]
        [http.routers.apiRedirect]
          entryPoints = ["http"]
          Middlewares = ["apiRediredctEncodeSlash", "apiRedirect"]
          Rule = "PathPrefix(`/entities`) && HeadersRegexp(`Accept`,`application/json`)"
          Service = "default"

        [http.routers.uiRedirect]
          entryPoints = ["http"]
          Middlewares = ["uiRedirect"]
          Rule = "PathPrefix(`/entities`) && HeadersRegexp(`Accept`,`text/html`)"
          Service = "default"

        [http.routers.gateway]
          entryPoints = ["http"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}auth`)"
          Service = "gateway"

        [http.routers.jupyterhub]
          entryPoints = ["http"]
          Middlewares = ["auth-jupyterhub", "common", "jupyterhub" ]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}jupyterhub`)"
          Service = "jupyterhub"

{{ if eq .Values.global.anonymousSessions.enabled false }}
        [http.routers.notebooks]
          entryPoints = ["http"]
          Middlewares = ["auth-jupyterhub", "common", "notebooks"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}notebooks`)"
          Service = "jupyterhub"
{{ end }}

        [http.routers.webhooks]
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "webhooks"]
          Rule = "Path(`{{ .Values.gatewayServicePrefix | default "/api/" }}projects/{project-id}/graph/webhooks{endpoint:(.*)}`)"
          Service = "webhooks"

        [http.routers.graphstatus]
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "graphstatus"]
          Rule = "Path(`{{ .Values.gatewayServicePrefix | default "/api/" }}projects/{project-id}/graph/status{endpoint:(.*)}`)"
          Service = "webhooks"

        [http.routers.graphql]
          entryPoints = ["http"]
          Middlewares = ["common", "graphql"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}graphql`)"
          Service = "graphql"

        [http.routers.datasets]
          entryPoints = ["http"]
          Middlewares = ["common", "knowledgeGraph"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}datasets`)"
          Service = "knowledgeGraph"

        [http.routers.direct]
          # This is to access undocumented APIs in GitLab
          entryPoints = ["http"]
          Middlewares = [
            "direct"
            {{- if .Values.global.gitlab.enabled -}}
            ,"gitlabOnly"
            {{- end }}
          ]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}direct/`)"
          Service = "gitlab"

        [http.routers.gitlab]
          # Currently gitlab acts as fallback backend service, we
          # therefore fix the priority of this router to the lowest
          # possible value.
          priority = 1
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "gitlabApi"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}`)"
          Service = "gitlab"

        [http.routers.renku]
          entryPoints = ["http"]
          Middlewares = ["auth-renku", "common"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}renku`)"
          Service = "core"

        [http.routers.kg]
          entryPoints = ["http"]
          Middlewares = ["auth-gitlab", "common", "kg", "knowledgeGraph"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}kg`)"
          Service = "knowledgeGraph"

      [http.middlewares]

        # We assume entity IDs which are URL-safe except <namespace>/<project-name>
        # IDs (so all IDs with one forward-slash) for projets which we capture and
        # URL-encode explicitly. Full URL-encoding is tricky with GO regexes.
        [http.middlewares.apiRediredctEncodeSlash.redirectRegex]
          regex = "http://(.*)/entities/([^/]*)/([^/]*)/(.*)"
          replacement = "{{(include "gateway.protocol" .)}}://${1}/api/${2}/${3}%2F${4}"

        [http.middlewares.apiRedirect.redirectRegex]
          regex = "http://(.*)/entities/(.*)"
          replacement = "{{(include "gateway.protocol" .)}}://${1}/api/${2}"

        [http.middlewares.uiRedirect.redirectRegex]
          regex = "http://(.*)/entities/(.*)"
          replacement = "{{(include "gateway.protocol" .)}}://${1}/${2}"

        [http.middlewares.commonWithCookie.chain]
          {{- if .Values.development }}
          middlewares = ["general-ratelimit", "api", "development"]
          {{- else }}
          middlewares = ["general-ratelimit", "api"]
          {{- end }}

        [http.middlewares.common.chain]
          middlewares = ["noCookies", "commonWithCookie"]

        [http.middlewares.noCookies.headers]
          [http.middlewares.noCookies.headers.CustomRequestHeaders]
            Cookie = ""

        [http.middlewares.api.StripPrefix]
          prefixes = ["/api"]

        [http.middlewares.development.headers]
          isDevelopment = true

        [http.middlewares.gitlabOnly.AddPrefix]
          prefix = "/"

        [http.middlewares.gitlabApi.AddPrefix]
          prefix = "/api/v4"

        [http.middlewares.jupyterhub.ReplacePathRegex]
          regex = "^/jupyterhub/(.*)"
          replacement = "/jupyterhub/hub/api/$1"

{{ if eq .Values.global.anonymousSessions.enabled false }}
        [http.middlewares.notebooks.ReplacePathRegex]
          regex = "^/notebooks/(.*)"
          replacement = "/jupyterhub/services/notebooks/$1"
{{ end }}

        [http.middlewares.auth-gitlab.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=gitlab"
          trustForwardHeader = true
          authResponseHeaders = ["Authorization"]

        [http.middlewares.auth-jupyterhub.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=jupyterhub"
          trustForwardHeader = true
          authResponseHeaders = ["Authorization"]

        [http.middlewares.auth-renku.forwardauth]
          address = "http://{{ template "gateway.fullname" . }}-auth/?auth=renku"
          trustForwardHeader = true
          authResponseHeaders = ["Authorization", "Renku-user-id", "Renku-user-fullname", "Renku-user-email"]

        [http.middlewares.webhooks.ReplacePathRegex]
          regex = "^/projects/([^/]*)/graph/webhooks(.*)"
          replacement = "/projects/$1/webhooks$2"

        [http.middlewares.graphstatus.ReplacePathRegex]
          regex = "^/projects/([^/]*)/graph(.*)"
          replacement = "/projects/$1/events$2"

        [http.middlewares.graphql.ReplacePathRegex]
          regex = "/graphql"
          replacement = "/knowledge-graph/graphql"

        [http.middlewares.knowledgeGraph.AddPrefix]
          prefix = "/knowledge-graph"

        [http.middlewares.direct.ReplacePathRegex]
          regex = "^/api/direct/(.*)"
          replacement = "/$1"

        [http.middlewares.general-ratelimit.ratelimit]
          extractorfunc = "{{ .Values.rateLimits.general.extractorfunc }}"
          [http.middlewares.general-ratelimit.ratelimit.rateset.rate0]
            period = "{{ .Values.rateLimits.general.period }}"
            average = {{ .Values.rateLimits.general.average }}
            burst = {{ .Values.rateLimits.general.burst }}

        [http.middlewares.kg.StripPrefix]
          prefixes = ["/kg"]

      [http.services]
        [http.services.gateway.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.gateway.LoadBalancer.servers]]
            url = "http://{{ template "gateway.fullname" . }}-auth/"
            weight = 1

        [http.services.gitlab.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.gitlab.LoadBalancer.servers]]
            url = {{ .Values.global.gitlab.url | default (printf "%s://gitlab.%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            weight = 1

        [http.services.jupyterhub.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.jupyterhub.LoadBalancer.servers]]
            url = {{ .Values.jupyterhub.url | default (printf "%s://%s/jupyterhub" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            weight = 1

        [http.services.webhooks.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.webhooks.LoadBalancer.servers]]
            url = {{ .Values.graph.webhookService.hostname | default (printf "http://%s-webhook-service" .Release.Name ) | quote }}
            weight = 1

        [http.services.graphql.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.graphql.LoadBalancer.servers]]
          url = {{ .Values.graph.knowledgeGraph.hostname | default (printf "http://%s-knowledge-graph" .Release.Name ) | quote }}
            weight = 1

        [http.services.knowledgeGraph.LoadBalancer]
          method = "drr"
          [[http.services.knowledgeGraph.LoadBalancer.servers]]
          url = {{ .Values.graph.knowledgeGraph.hostname | default (printf "http://%s-knowledge-graph" .Release.Name ) | quote }}
            weight = 1

        [http.services.core.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.core.LoadBalancer.servers]]
          url = {{ .Values.core.hostname | default (printf "http://%s-core" .Release.Name ) | quote }}
            weight = 1

        # We need a default backend, should never be hit
        [http.services.default.LoadBalancer]
          method = "drr"
          [[http.services.default.LoadBalancer.servers]]
          url = {{ printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain | quote }}
            weight = 1

{{ if .Values.global.anonymousSessions.enabled }}
  rules-tmp.toml: |
    [http]
      [http.routers]

        # What we do here is equivalent to using a second traefik instance in front
        # of the two notebook services.
        # - If the regular jupyterhub-auth finds a JH oauth token, we use
        #   it and forward to the normal notebook service.
        # - Otherwise we use the notebooks-tmp service.


        # Note that routers are applied in the order of their priority,
        # where the priority is derived from the length of the rule
        # (longer -> more specific -> higher priority). This priority can be
        # explicitly overwritten.

        [http.routers.notebooksFirstPass]
          priority=1001
          entryPoints = ["http"]
          Middlewares = ["auth-jupyterhub", "secondPassPath"]
          Rule = "PathPrefix(`{{ .Values.gatewayServicePrefix | default "/api/" }}notebooks`)"
          Service = "notebooksSecondPass"

        [http.routers.notebooksSecondPassTmp]
          priority=1002
          entryPoints = ["http"]
          Middlewares = ["commonWithCookie", "notebooksTmp"]
          Rule = "PathPrefix(`/notebooks-second-pass`)"
          Service = "jupyterhubTmp"

        [http.routers.notebooksSecondPassRegular]
          priority=1003
          entryPoints = ["http"]
          Middlewares = ["common", "notebooks"]
          Rule = "PathPrefix(`/notebooks-second-pass`) && HeadersRegexp(`Authorization`, `token`)"
          Service = "jupyterhub"

      [http.middlewares]

        [http.middlewares.secondPassPath.ReplacePathRegex]
          regex = "/api/notebooks/(.*)"
          replacement = "/notebooks-second-pass/$1"

        [http.middlewares.notebooks.ReplacePathRegex]
          regex = "^/notebooks-second-pass/(.*)"
          replacement = "/jupyterhub/services/notebooks/$1"

        [http.middlewares.notebooksTmp.ReplacePathRegex]
          regex = "^/notebooks-second-pass/(.*)"
          replacement = "/jupyterhub-tmp/services/notebooks/$1"


      [http.services]

        [http.services.notebooksSecondPass.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.notebooksSecondPass.LoadBalancer.servers]]
            url = "http://{{ template "gateway.fullname" . }}"
            weight = 1


        [http.services.jupyterhubTmp.LoadBalancer]
          method = "drr"
          passHostHeader = false
          [[http.services.jupyterhubTmp.LoadBalancer.servers]]
            url = {{ .Values.jupyterhub.tmpUrl | default (printf "%s://%s/jupyterhub-tmp" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            weight = 1
{{ end }}
