apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "renku-gateway.fullname" . }}
  labels:
    app: {{ template "renku-gateway.name" . }}
    chart: {{ template "renku-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "renku-gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "renku-gateway.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: BASE_URL
              value: {{ .Values.baseUrl | default (printf "%s://%s" (include "renku-gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_URL
              value: {{ .Values.gitlabUrl | default (printf "%s://gitlab.%s" (include "renku-gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_CLIENT_ID
              value: {{ .Values.gitlabClientId | default "renku-gateway" | quote }}
            - name: JUPYTERHUB_URL
              value: {{ .Values.jupyterhubUrl | default (printf "%s://jupyterhub.%s" (include "renku-gateway.protocol" .) .Values.global.renku.domain) | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
