apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}
        release: {{ .Release.Name }}
        {{ include "call-nested" (list . "redis" "redis.fullname") }}-client: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: HOST_NAME
              value: {{ .Values.hostName | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: RENKU_ENDPOINT
              value: {{ .Values.renkuEndpoint | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_URL
              value: {{ .Values.gitlabUrl | default (printf "%s://%s/gitlab" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_CLIENT_SECRET
              value: {{ .Values.gitlabClientSecret | default .Values.global.gateway.gitlabClientSecret | quote }}
            - name: GITLAB_CLIENT_ID
              value: {{ .Values.gitlabClientId | default .Values.global.gateway.gitlabClientId | quote }}
            - name: GITLAB_PASS
              value: {{ .Values.gitlabSudoToken | default .Values.global.gitlab.sudoToken | quote }}
            - name: JUPYTERHUB_URL
              value: {{ .Values.jupyterhubUrl | default (printf "%s://%s/jupyterhub" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloakUrl | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GATEWAY_SERVICE_PREFIX
              value: {{ .Values.gatewayServicePrefix | default "/api/" | quote }}
            - name: OIDC_CLIENT_SECRET
              value: {{ .Values.oidcClientSecret | default .Values.global.gateway.clientSecret | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidcClientId | default "gateway" | quote }}
            - name: GATEWAY_REDIS_HOST
              value: {{ include "call-nested" (list . "redis" "redis.fullname") }}-master
            - name: GATEWAY_SECRET_KEY
              value: {{ .Values.secretKey | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
