apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gateway.fullname" . }}-revproxy
  labels:
    app: {{ template "gateway.name" . }}-revproxy
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if not .Values.reverseProxy.autoscaling.enabled }}
  replicas: {{ .Values.reverseProxy.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.reverseProxy.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}-revproxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}-revproxy
        release: {{ .Release.Name }}
      {{- with .Values.reverseProxy.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      automountServiceAccountToken: {{ .Values.global.debug }}
      initContainers:
        {{- include "certificates.initContainer" . | nindent 8 }}
      containers:
        - name: revproxy
          image: "{{ .Values.reverseProxy.image.repository }}:{{ .Values.reverseProxy.image.tag }}"
          imagePullPolicy: {{ .Values.reverseProxy.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: REVPROXY_RENKU_BASE_URL
              value: {{ .Values.hostName | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: REVPROXY_EXTERNAL_GITLAB_URL
              value: {{ .Values.gitlabUrl | default "" | quote }}
            - name: REVPROXY_ALLOW_ORIGIN
              value: {{ join "," .Values.allowOrigin | quote }}
            - name: REVPROXY_RENKU_SERVICES_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: REVPROXY_RENKU_SERVICES_WEBHOOK
              value: {{ .Values.graph.webhookService.hostname | default (printf "http://%s-webhook-service" .Release.Name ) | quote }}
            - name: REVPROXY_RENKU_SERVICES_KG
              value: {{ .Values.graph.knowledgeGraph.hostname | default (printf "http://%s-knowledge-graph" .Release.Name ) | quote }}
            - name: REVPROXY_RENKU_SERVICES_NOTEBOOKS
              value: {{ .Values.notebooks.hostname | default (printf "http://%s-notebooks" .Release.Name ) | quote }}
            - name: REVPROXY_RENKU_SERVICES_CORE_NAME
              value: {{ .Values.core.basename | default (printf "%s-core" .Release.Name ) | quote }}
            - name: REVPROXY_RENKU_SERVICES_CORE_VERSIONS
              value: {{- range $i, $version := .Values.core.versions -}}{{ if $i }},{{ end }}{{ $version.name }};{{ $version.prefix }}{{- end -}}
            - name: REVPROXY_RENKU_SERVICES_CORE_MAIN_VERSION
              value: {{ .Values.core.versions.latest.name | quote }}
            - name: REVPROXY_RENKU_SERVICES_AUTH
              value: {{ printf "http://%s-gateway-auth" .Release.Name }}
            - name: REVPROXY_PORT
              value: "8080"
            - name: REVPROXY_METRICS_ENABLED
              value: {{ .Values.reverseProxy.metrics.enabled | quote }}
            - name: REVPROXY_METRICS_PORT
              value: {{ .Values.reverseProxy.metrics.port | quote }}
            - name: REVPROXY_RATE_LIMITS_ENABLED
              value: {{ .Values.rateLimits.general.enabled | quote }}
            - name: REVPROXY_RATE_LIMITS_AVERAGE
              value: {{ .Values.rateLimits.general.average | quote }}
            - name: REVPROXY_RATE_LIMITS_BURST
              value: {{ .Values.rateLimits.general.burst | quote }}
          volumeMounts:
            {{- include "certificates.volumeMounts.system" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /revproxy/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /revproxy/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 2
          resources:
            {{ toYaml .Values.reverseProxy.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        {{- include "certificates.volumes" . | nindent 8 }}
