apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}
        release: {{ .Release.Name }}
        {{ include "call-nested" (list . "redis" "redis.fullname") }}-client: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: HOST_NAME
              value: {{ .Values.hostName | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: RENKU_ENDPOINT
              value: {{ .Values.renkuEndpoint | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_URL
              value: {{ .Values.gitlabUrl | default (printf "%s://%s/gitlab" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GATEWAY_ENV
              value: {{ .Values.gatewayEnv | default "deployment" | quote }}
            - name: GITLAB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: gitlabClientSecret
            - name: GITLAB_CLIENT_ID
              value: {{ .Values.gitlabClientId | default .Values.global.gateway.gitlabClientId | quote }}
            - name: JUPYTERHUB_URL
              value: {{ .Values.jupyterhub.url | default (printf "%s://%s/jupyterhub" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: JUPYTERHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: jupyterhubClientSecret
            - name: JUPYTERHUB_CLIENT_ID
              value: {{ .Values.jupyterhub.clientId | quote }}
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloakUrl | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GATEWAY_SERVICE_PREFIX
              value: {{ .Values.gatewayServicePrefix | default "/api/" | quote }}
            - name: GATEWAY_REDIS_HOST
              value: {{ include "call-nested" (list . "redis" "redis.fullname") }}-master
            - name: GATEWAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: gatewaySecret
            - name: GATEWAY_ALLOW_ORIGIN
              value: {{ .Values.allowOrigin | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidcClientId | default "gateway" | quote }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: oidcClientSecret
            - name: SPARQL_ENDPOINT
              value: {{ .Values.graph.sparql.endpoint | default (printf "http://%s-jena:3030/%s/sparql" .Release.Name .Release.Namespace ) | quote }}
            - name: SPARQL_USERNAME
              value: {{ required "Please specify a username for the SPARQL endpoint." .Values.graph.sparql.username | quote }}
            - name: SPARQL_PASSWORD
              value: {{ required "Please specify a password for the SPARQL endpoint user." .Values.graph.sparql.password | quote }}
            - name: WEBHOOK_SERVICE_HOSTNAME
              value: {{ .Values.graph.webhookService.hostname | default (printf "http://%s-graph-webhook-service" .Release.Name ) | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
