---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "gateway.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: admin
              containerPort: 8080
          args:
            - --configfile=/config/traefik.toml
          volumeMounts:
            - mountPath: /config
              name: config
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "gateway.fullname" . }}-auth
  labels:
    app: {{ template "gateway.name" . }}-auth
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}-auth
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "gateway.name" . }}-auth
        release: {{ .Release.Name }}
        {{ include "call-nested" (list . "redis" "redis.fullname") }}-client: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.auth.repository }}:{{ .Values.image.auth.tag }}"
          imagePullPolicy: {{ .Values.image.auth.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: HOST_NAME
              value: {{ .Values.hostName | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_URL
              value: {{ .Values.gitlabUrl | default (printf "%s://%s/gitlab" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: GITLAB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: gitlabClientSecret
            - name: GITLAB_CLIENT_ID
              value: {{ .Values.gitlabClientId | default .Values.global.gateway.gitlabClientId | quote }}
            - name: JUPYTERHUB_URL
              value: {{ .Values.jupyterhub.url | default (printf "%s://%s/jupyterhub" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
            - name: JUPYTERHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: jupyterhubClientSecret
            - name: JUPYTERHUB_CLIENT_ID
              value: {{ .Values.jupyterhub.clientId | quote }}
            - name: KEYCLOAK_URL
              value: {{ .Values.keycloakUrl | default (printf "%s://%s" (include "gateway.protocol" .) .Values.global.renku.domain) | quote }}
              {{ if .Values.global.keycloak.realm }}
            - name: KEYCLOAK_REALM
              value: {{ .Values.global.keycloak.realm | quote }}
              {{ end }}
            - name: GATEWAY_SERVICE_PREFIX
              value: {{ .Values.gatewayServicePrefix | default "/api/" | quote }}
            - name: GATEWAY_REDIS_HOST
              value: {{ include "call-nested" (list . "redis" "redis.fullname") }}-master
            - name: GATEWAY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: gatewaySecret
            - name: GATEWAY_ALLOW_ORIGIN
              value: {{ .Values.allowOrigin | quote }}
            - name: OIDC_CLIENT_ID
              value: {{ .Values.oidcClientId | default "renku" | quote }}
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "gateway.fullname" . }}
                  key: oidcClientSecret
            - name: OLD_GITLAB_LOGOUT
              value: {{ .Values.oldGitLabLogout | quote }}
            - name: WEBHOOK_SERVICE_HOSTNAME
              value: {{ .Values.graph.webhookService.hostname | default (printf "http://%s-graph-webhook-service" .Release.Name ) | quote }}
            {{ if .Values.global.anonymousSessions.enabled }}
            - name: ANONYMOUS_SESSIONS_ENABLED
              value: "true"
            {{ end }}
            # Note that this is ok because we're enforcing HTTPS
            # further up the processing chain.
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "1"
            - name: SENTRY_DSN
              value: {{ .Values.sentry.dsn }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentry.environment }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
