{{- if or (gt (int .Values.reverseProxy.replicaCount) 1) (and .Values.reverseProxy.autoscaling.enabled (gt (int .Values.reverseProxy.autoscaling.minReplicas) 1)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "gateway.fullname" . }}-revproxy
  labels:
    app: {{ template "gateway.name" . }}-revproxy
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  maxUnavailable: 50%
  selector:
    matchLabels:
      app: {{ template "gateway.name" . }}-revproxy
      release: {{ .Release.Name }}
{{- end }}
