---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  oidcClientSecret: {{ .Values.oidcClientSecret | default .Values.global.gateway.clientSecret | b64enc | quote }}
  gitlabClientSecret: {{ .Values.global.gitlab.appSecret | b64enc | quote }}
  jupyterhubClientSecret: {{ required "Fill in .Values.jupyterhub.clientSecret with `openssl rand -hex 32`"  .Values.jupyterhub.clientSecret | b64enc | quote }}
  gatewaySecret: {{ required "Fill in .Values.secretKey with `openssl rand -hex 32`"  .Values.secretKey | b64enc | quote }}
  cliClientSecret: {{ .Values.cliClientSecret | default .Values.global.gateway.cliClientSecret | b64enc | quote }}
