apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gateway.fullname" . }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  gitlabSudoToken: {{ .Values.gitlabSudoToken | default .Values.global.gitlab.sudoToken | b64enc | quote }}
  oidcClientSecret: {{ .Values.oidcClientSecret | default .Values.global.gateway.clientSecret | b64enc | quote }}
  gitlabClientSecret: {{ .Values.gitlabClientSecret | default .Values.global.gateway.gitlabClientSecret | b64enc | quote }}
  jupyterhubClientSecret: {{ required "Fill in .Values.jupyterhub.clientSecret with `openssl rand -hex 32`"  .Values.jupyterhub.clientSecret | b64enc | quote }}
  gatewaySecret: {{ .Values.secretKey | b64enc | quote }}
